<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Enter User Name Steps completed]]>
    </line>
    <line>
      <![CDATA[Clicked on Next Button Steps completed]]>
    </line>
    <line>
      <![CDATA[Enter OTP Steps completed]]>
    </line>
    <line>
      <![CDATA[Verify OTP Steps completed]]>
    </line>
    <line>
      <![CDATA[Enter Password Steps completed]]>
    </line>
    <line>
      <![CDATA[Capture the Home Page Steps completed]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="16194" started-at="2019-07-03T07:10:56Z" finished-at="2019-07-03T07:11:12Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="16194" started-at="2019-07-03T07:10:56Z" finished-at="2019-07-03T07:11:12Z">
      <class name="Login_Tests.Login_Test">
        <test-method status="PASS" signature="preCondition()[pri:0, instance:Login_Tests.Login_Test@3bb9a3ff]" name="preCondition" is-config="true" duration-ms="6087" started-at="2019-07-03T12:40:56Z" finished-at="2019-07-03T12:41:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondition -->
        <test-method status="PASS" signature="InvalidLoginToHomePage()[pri:0, instance:Login_Tests.Login_Test@3bb9a3ff]" name="InvalidLoginToHomePage" duration-ms="5" started-at="2019-07-03T12:41:02Z" finished-at="2019-07-03T12:41:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidLoginToHomePage -->
        <test-method status="FAIL" signature="LoginToHomePage()[pri:0, instance:Login_Tests.Login_Test@3bb9a3ff]" name="LoginToHomePage" duration-ms="9996" started-at="2019-07-03T12:41:02Z" finished-at="2019-07-03T12:41:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Help & Support hh] but found [Help & Support]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Help & Support hh] but found [Help & Support]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at Login_Tests.Login_Test.LoginToHomePage(Login_Test.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Enter User Name Steps completed]]>
            </line>
            <line>
              <![CDATA[Clicked on Next Button Steps completed]]>
            </line>
            <line>
              <![CDATA[Enter OTP Steps completed]]>
            </line>
            <line>
              <![CDATA[Verify OTP Steps completed]]>
            </line>
            <line>
              <![CDATA[Enter Password Steps completed]]>
            </line>
            <line>
              <![CDATA[Capture the Home Page Steps completed]]>
            </line>
          </reporter-output>
        </test-method> <!-- LoginToHomePage -->
        <test-method status="PASS" signature="postConditoin()[pri:0, instance:Login_Tests.Login_Test@3bb9a3ff]" name="postConditoin" is-config="true" duration-ms="85" started-at="2019-07-03T12:41:12Z" finished-at="2019-07-03T12:41:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postConditoin -->
      </class> <!-- Login_Tests.Login_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
